### ISSUE TITLE
Autorefill doesn't work with wheat seeds

### ISSUE THREAD

**Issue by thada2607** [MLG-Fortress/AutomaticInventory#24]
As the title said. I put all the wheat seeds in a slot to a composter and it didn't get refilled, I also threw it out and it didn't get refilled either.

**Comment by RoboMWM** [comment]
This is probably a feature request then?

**Comment by thada2607** [comment]
> This is probably a feature request then?

Isn't it an issue?

**Comment by RoboMWM** [comment]
How is this an issue? Was this a feature that's broken?

**Comment by thada2607** [comment]
> How is this an issue? Was this a feature that's broken?

I'm confused, isn't the plugin's purpose to refill items in your hotbar in whatever activity you do to drain it?

**Comment by thada2607** [comment]
> How is this an issue? Was this a feature that's broken?

I'm confused, isn't the plugin's purpose to refill items in the hotbar regardless of whatever activity draining it?

**Comment by thada2607** [comment]
> How is this an issue? Was this a feature that's broken?

I'm confused, isn't the plugin's purpose to refill items in the hotbar regardless of whatever activity draining them?

**Comment by RoboMWM** [comment]
>  isn't the plugin's purpose to refill items in the hotbar regardless of whatever activity draining them?

The plugin does not know how every item is used. It will refill tools. I'm not sure if disposable items are supposed to be refilled, but if so, it's probably because it's only looking at interact event - and I'm not sure if those items are accounted for. There isn't a "farming items" tag or anything of the sort, nor am I aware of there being such a feature.

Please note that I picked up this plugin, so feel free to point out in the plugin's description where this feature (or objective) is listed. If it's only implicit, I'll determine if it's part of the featureset.

**Comment by thada2607** [comment]
I kinda see it. So where can I post my suggestions?

**Comment by RoboMWM** [comment]
Here is fine, but note the readme

**Comment by thada2607** [comment]
Here are my suggestions:
1. Refills seeds (or any disposable items) after users spend it all to fill composters, also refills it when players throw it all out, the point is to make the plugin work with seeds (disposable items) like it would with any other items.
2. Manually sorting by hotkeys (middle click or something).
An implement of these would be appreciated. And thank you for your contribution.

**Comment by RoboMWM** [comment]
make a separate issue for 2., and either revise or make another issue for 1.
