### ISSUE TITLE
Exclude items by name from the auto deposit process

### ISSUE THREAD

**Issue by TheoRetisch1** [MLG-Fortress/AutomaticInventory#36]
It would be great if one could exclude items by name from the auto deposit process. For example, if an item has "_*_" in its name, it should not be automatically sorted. This way, equipment items that are known not to constantly clog the hotbar can be deliberately excluded without having to restrict the sorting process for all tools of this type in the config.
The namings which should not be sorted away could be defined in the config under "_Excluded Items_" as regex expression. This would give the feature a high degree of flexibility.

**Comment by RoboMWM** [comment]
Ok, so you want to add a config item that does a regex pattern search on the item's [DisplayName](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/meta/ItemMeta.html#getDisplayName())?

**As a server admin**
**I want** to exclude items that match a certain regex pattern from being auto-deposited
**So that** I can retain specific items, even if they are not in the hotbar

Scenario: I'm a player
**Given** a config string has been put in the config
**When** I shift left-click a chest
**Or** execute `/depositall`
**Then** all items not in the hotbar will be deposited
**Except** for any items' DisplayName that contains the config string

**Comment by TheoRetisch1** [comment]
Yeah that would be great. Thanks for the clear structure :)

**Comment by RoboMWM** [comment]
Since you didn't ask for regex, and regex syntax isn't exactly straightforward, would just a simple match be sufficient? I've updated the above story to reflect that.

**Comment by RoboMWM** [comment]
Let me know if this works. Leaving the string empty (the default) disables the feature. https://ci.appveyor.com/project/RoboMWM39862/automaticinventory-jw57t/builds/34945989/artifacts

**Comment by TheoRetisch1** [comment]
Awesome! It works like a charm, thank you :)
